feather-falling-effectiveness-multiplier: 1
movement-speed-multiplier: 1
sprint-speed-multiplier: 1
mending-effectiveness-multiplier: 1
thorns-effectiveness-multiplier: 1
knockback-effectiveness-multiplier: 1
punch-effectiveness-multiplier: 1
respiration-effectiveness-multiplier: 1
soul-speed-multiplier: 1
depth-strider-multiplier: 1